app:
  env: dev
  name: kekai's blog

mysql:
  uri: root:@tcp(localhost)/goblog
  host: localhost
  user: root
  pass: 
  max_idle_conns: 2
  max_open_conns: 5
  log_mode: true
  ## minutes
  conn_max_lifetime: 60