app:
  env: pre
  name: kekai's blog
  token: b8700fbb63d18d29164285cbb996c5f3

mysql:
  uri: root:@tcp(localhost)/goblog?parseTime=true
  host: localhost
  user: root
  pass: 
  max_idle_conns: 2
  max_open_conns: 5
  log_mode: true
  ## minutes
  conn_max_lifetime: 60